### ISSUE TITLE
Unable to connect Muse 1 on Windows 10

### ISSUE THREAD

**Issue by ijwzac** [Zanderlabs/IXR-Suite#5]
Hi, I am a tester who want to use this suite. Here are the problems I found.

First, I can't connect to Muse 1 with v0.4. I contacted Cangar and he confirmed that my steps are correct. I see these three lines in Console:
```
[info] found 1 BLE adapter(s)
[info] Found Muse device
[error] Failed to connect to Muse Device
```

Then, I debugged IXR-Suite with VSCode thanks to your detailed tutorial and found some clues. 
The root cause was .venv\Lib\site-packages\brainflow\board_shim.py:1142
Function call `.prepare_session()` never returns. And this function is in `.venv\Lib\site-packages\brainflow\lib\BoardController.dll` so I didn't look further
```
    def prepare_session(self) -> None:
        """prepare streaming sesssion, init resources, you need to call it before any other BoardShim object methods"""

        res = BoardControllerDLL.get_instance().prepare_session(self.board_id, self.input_json)
        if res != BrainFlowExitCodes.STATUS_OK.value:
            raise BrainFlowError('unable to prepare streaming session', res)
```

I found that upgrading the version of brainflow can partially solve this problem. Their newest version 5.9.0 still blocks at `.prepare_session()`, however, 5.6.0 sometimes works and this function sometimes returns. Also note that in their 5.6.0 release they said: "[fixes for Muse connection issue on Windows](https://github.com/brainflow-dev/brainflow/releases/tag/5.6.0)"

However, now I am having a new error (at least now we have an error code!). The return value `res` above is 15 but `BrainFlowExitCodes.STATUS_OK.value` is 0, so the if branch will be chosen and I am seeing the raised `BrainFlowError`

I don't know if you know what's error 15 here. **Do you think I should report at brainflow's github instead?**

Some other notes: 
(1) I bought a new bluetooth antenna but it didn't help. 
(2) I can get IXR-Suite and this headband to work on another Win10 Desktop (i7-7700 CPU), so the headband is OK. Even played SkyrimVR with Real Virtual Magic mod for some time. It has an issue I'd like to report later, but the experience is great!
(3) Given that my desktop that works has Intel CPU and Intel motherboard, and the one doesn't work has AMD CPU and AM4 motherboard with notorious USB voltage unstable issues, my theory is that there are some compatibility issues.

My specs:
```
Muse 2016
Windows 10 Version 22H2
CPU: AMD 5800X3D
Motherboard: AM4 AsRock B450M Pro4
```

**Comment by MariusKlug** [comment]
Thank you for your test and detailed feedback! According to the brainflow doc, the error code 15 means that the board was not created (https://brainflow.readthedocs.io/en/stable/UserAPI.html?highlight=error%2015#_CPPv4N9brainflow18BrainFlowExitCodes23BOARD_NOT_CREATED_ERRORE). I think there is sufficient grounds to suspect that this bug is due to brainflow itself, so yes, please go ahead and contact them. There's a slack channel for support: https://brainflow.org/2020-03-23-slack/

**Comment by ijwzac** [comment]
Thanks for your reply! I will ask brainflow to look into the issue, and now I will close this issue
